### ISSUE TITLE
All queues are cleared every 24 hours when Heroku restarts dynos

### ISSUE THREAD

**Issue by indirect** [japaric/homu-on-heroku#5]
Homu doesn't listen to PRs that aren't in the queue list... but even after manually synchronizing every single repository, every queue gets completely cleared anytime the dyno restarts. That includes every night, when Heroku forcibly restarts all web dynos after 24 hours.

How do I preserve the queues long enough that I can actually use the bot to review and merge PRs?

Thanks!

**Comment by japaric** [comment]
Yes, this is a problem.

> when Heroku forcibly restarts all web dynos after 24 hours.

My understanding is that this changed and Heroku can now keep dynos running uninterruptedly as long as you don't exceed your monthly quota. However, if Homu is inactive for more than 30 mins then Heroku will make the dyno sleep. For the latter problem, I have a bash script that "polls" my Homu webpage every 10 minutes; that keeps the dyno awake:

``` bash
while sleep $((10*60)); do
    echo PING @ $(date +"%Y-%m-%dT%H:%M:%SZ")
    curl -s https://homu.herokuapp.com > /dev/null
done
```

> How do I preserve the queues long enough that I can actually use the bot to review and merge PRs?

You could move to Heroku's Hobby tier to get rid of sleeps. Or you could host Homu on a different server. There's also [aelitabot.xyz](https://aelitabot.xyz/) which hosts Homu instances for you; I haven't tried that tough.
